baseUrl = "https://jkd.rickyaziz.my.id/"
title = 'ACSL | Jaringan Komputer Dasar'

# -------------------------------------------------------------------
# Module (tema & dependensi)
# -------------------------------------------------------------------
[module]
  [module.hugoVersion]
    extended = true
    min = "0.140.0"

  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false

  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

# -------------------------------------------------------------------
# Parameter utama untuk docs
# -------------------------------------------------------------------
[params.docs]
  title = "ACSL Docs"
  darkMode = true
  themeColor = "magenta"
  favicon = "/images/favicon.png"
  titleIcon = true
  sidebarIcons = true
  breadcrumbs = true
  toc = true
  tocMobile = true
  scrollSpy = true
  backToTop = true
  descriptions = true
  navDesc = true
  navDescTrunc = 30
  listDescTrunc = 100
  prism = true
  prismTheme = "lotusdocs"

# -------------------------------------------------------------------
# Parameter global
# -------------------------------------------------------------------
[params]
  logo = "/images/logo2.svg"
  math = true   # 

# -------------------------------------------------------------------
# Footer Configuration
# -------------------------------------------------------------------
[params.footer]
  copyright = "Â© :YEAR: [Advanced Computer System Laboratory](https://gunadarma.ac.id). Built with [LotusDocs](https://github.com/colinwilson/lotusdocs)"

# -------------------------------------------------------------------
# Social Media & Contact
# -------------------------------------------------------------------
[params.social]
  github = "https://github.com/Advanced-Computer-System-Laboratory"
  instagram = "labacsl_ug"
  email = "info@gunadarma.ac.id"
  website = "https://gunadarma.ac.id"

# -------------------------------------------------------------------
# Menu utama
# -------------------------------------------------------------------
[menu]
  [[menu.primary]]
    name  = "Docs"
    url = "docs/"
    identifier = "docs"
    weight = 10

# -------------------------------------------------------------------
# Markdown renderer
# -------------------------------------------------------------------
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true   # wajib untuk render HTML dan KaTeX
